"""Curated public satpy SEVIRI composites (100) for gallery + Dynamic Image.

Selected from satpy's built-in SEVIRI / VISIR recipes that work from MSG L1B
native files alone (no NWCSAF/PPS / BlackMarble / HRV-stacked resampling).
Additional app-local extras are standard EUMETSAT-style RGBs built only from
SEVIRI IR/WV/VIS channels on the common 3 km grid.
"""

from __future__ import annotations

COMPOSITE_NAMES: list[str] = [
    # Core EUMETSAT / satpy public RGBs (3 km grid)
    "natural_color",
    "natural_color_nocorr",
    "natural_color_raw",
    "natural_enh",
    "overview",
    "overview_raw",
    "airmass",
    "dust",
    "ash",
    "convection",
    "fog",
    "night_fog",
    "day_microphysics",
    "day_microphysics_winter",
    "night_microphysics",
    "night_microphysics_tropical",
    "24h_microphysics",
    "day_severe_storms",
    "day_severe_storms_tropical",
    "snow",
    "green_snow",
    "cloudtop",
    "cloudtop_daytime",
    "colorized_ir_clouds",
    "ir_overview",
    "ir_cloud_day",
    "ir108_3d",
    "overshooting_tops",
    "natural_with_night_fog",
    "natural_color_raw_with_night_ir",
    "night_ir_alpha",
    "rocket_plume_night",
    # App-local extras (satpy_config) — public-style SEVIRI-only RGBs
    "water_vapors1",
    "water_vapors2",
    "fire_temperature_eumetsat",
    "cloud_convective_storms",
    "dust_cloud",
    "ir_window_sandwich",
    "airmass_jet",
    "night_microphysics_simple",
    "wv_diff_rgb",
    "split_window_rgb",
    "ozone_airmass",
    "thermal_triplet",
    "moisture_ridge",
    "tropopause_fold",
    "cold_cloud_tops",
    "night_convection",
    "so2_proxy",
    "low_cloud_night",
    # Additional SEVIRI-only diagnostic RGBs (unique channel assignments)
    "upper_tropospheric_wv",
    "mid_tropospheric_wv",
    "lower_tropospheric_wv",
    "wv_layer_gradient",
    "dry_intrusion_rgb",
    "subtropical_jet_rgb",
    "moisture_transport_rgb",
    "upper_level_dynamics",
    "tropopause_moisture",
    "stratospheric_intrusion",
    "enhanced_dust_rgb",
    "mineral_dust_rgb",
    "desert_dust_night",
    "airborne_dust_proxy",
    "volcanic_ash_enhanced",
    "volcanic_so2_enhanced",
    "silicate_ash_rgb",
    "ash_dust_discrimination",
    "split_window_ash",
    "cloud_phase_thermal",
    "cloud_height_thermal",
    "cloud_top_temperature_rgb",
    "cirrus_detection_rgb",
    "thin_cirrus_rgb",
    "opaque_ice_cloud_rgb",
    "low_cloud_thermal",
    "fog_depth_rgb",
    "nocturnal_stratus_rgb",
    "cloud_layering_rgb",
    "ice_water_phase_rgb",
    "convective_growth_rgb",
    "severe_convection_thermal",
    "tropical_convection_thermal",
    "overshooting_top_thermal",
    "cold_ring_rgb",
    "storm_anvil_rgb",
    "rainfall_potential_rgb",
    "lightning_risk_proxy",
    "fire_hotspot_rgb",
    "fire_context_rgb",
    "wildfire_temperature_rgb",
    "smoke_dust_day",
    "burn_scar_rgb",
    "vegetation_contrast_rgb",
    "vegetation_moisture_rgb",
    "snow_cloud_discrimination",
    "daytime_cloud_phase_rgb",
    "daytime_fog_rgb",
    "coastal_aerosol_rgb",
    "land_ocean_contrast_rgb",
]

assert len(COMPOSITE_NAMES) == 100, len(COMPOSITE_NAMES)
assert len(COMPOSITE_NAMES) == len(set(COMPOSITE_NAMES)), "Duplicate composite names"

# Solar / daytime-reflectance composites: night blanks are expected.
SOLAR_DEPENDENT_COMPOSITES = frozenset(
    {
        "natural_color",
        "natural_color_nocorr",
        "natural_color_raw",
        "natural_enh",
        "overview",
        "overview_raw",
        "day_microphysics",
        "day_microphysics_winter",
        "day_severe_storms",
        "day_severe_storms_tropical",
        "snow",
        "green_snow",
        "cloudtop_daytime",
        "natural_with_night_fog",
        "natural_color_raw_with_night_ir",
        "cloud_convective_storms",
        "dust_cloud",
        "smoke_dust_day",
        "burn_scar_rgb",
        "vegetation_contrast_rgb",
        "vegetation_moisture_rgb",
        "snow_cloud_discrimination",
        "daytime_cloud_phase_rgb",
        "daytime_fog_rgb",
        "coastal_aerosol_rgb",
        "land_ocean_contrast_rgb",
    }
)

COMPOSITE_LABELS: dict[str, str] = {
    "natural_color": "Natural Colour",
    "natural_color_nocorr": "Natural Colour (no corr.)",
    "natural_color_raw": "Natural Colour (raw)",
    "natural_enh": "Natural Colour Enhanced",
    "overview": "Overview",
    "overview_raw": "Overview (raw)",
    "airmass": "Air Mass",
    "dust": "Dust",
    "ash": "Ash",
    "convection": "Convection",
    "fog": "Fog / Low Cloud",
    "night_fog": "Night Fog",
    "day_microphysics": "Day Microphysics",
    "day_microphysics_winter": "Day Microphysics (winter)",
    "night_microphysics": "Night Microphysics",
    "night_microphysics_tropical": "Night Microphysics (tropical)",
    "24h_microphysics": "24h Microphysics",
    "day_severe_storms": "Day Severe Storms",
    "day_severe_storms_tropical": "Day Severe Storms (tropical)",
    "snow": "Snow",
    "green_snow": "Green Snow",
    "cloudtop": "Cloud Top",
    "cloudtop_daytime": "Cloud Top (daytime)",
    "colorized_ir_clouds": "Colorized IR Clouds",
    "ir_overview": "IR Overview",
    "ir_cloud_day": "IR Cloud Day",
    "ir108_3d": "IR 10.8 3D",
    "overshooting_tops": "Overshooting Tops",
    "natural_with_night_fog": "Natural + Night Fog",
    "natural_color_raw_with_night_ir": "Natural Raw + Night IR",
    "night_ir_alpha": "Night IR (alpha)",
    "rocket_plume_night": "Rocket Plume (night)",
    "water_vapors1": "Water Vapour RGB 1",
    "water_vapors2": "Water Vapour RGB 2",
    "fire_temperature_eumetsat": "Fire Temperature (EUMETSAT)",
    "cloud_convective_storms": "Convective Storms RGB",
    "dust_cloud": "Dust / Cloud RGB",
    "ir_window_sandwich": "IR Window Sandwich",
    "airmass_jet": "Air Mass / Jet RGB",
    "night_microphysics_simple": "Night Microphysics (simple)",
    "wv_diff_rgb": "Water Vapour Difference RGB",
    "split_window_rgb": "Split-Window RGB",
    "ozone_airmass": "Ozone / Air Mass RGB",
    "thermal_triplet": "Thermal Triplet RGB",
    "moisture_ridge": "Moisture Ridge RGB",
    "tropopause_fold": "Tropopause Fold RGB",
    "cold_cloud_tops": "Cold Cloud Tops RGB",
    "night_convection": "Night Convection RGB",
    "so2_proxy": "SO₂ Proxy RGB",
    "low_cloud_night": "Low Cloud Night RGB",
    "upper_tropospheric_wv": "Upper-Tropospheric Water Vapour",
    "mid_tropospheric_wv": "Mid-Tropospheric Water Vapour",
    "lower_tropospheric_wv": "Lower-Tropospheric Water Vapour",
    "wv_layer_gradient": "Water-Vapour Layer Gradient",
    "dry_intrusion_rgb": "Dry Intrusion RGB",
    "subtropical_jet_rgb": "Subtropical Jet RGB",
    "moisture_transport_rgb": "Moisture Transport RGB",
    "upper_level_dynamics": "Upper-Level Dynamics RGB",
    "tropopause_moisture": "Tropopause Moisture RGB",
    "stratospheric_intrusion": "Stratospheric Intrusion RGB",
    "enhanced_dust_rgb": "Enhanced Dust RGB",
    "mineral_dust_rgb": "Mineral Dust RGB",
    "desert_dust_night": "Desert Dust at Night",
    "airborne_dust_proxy": "Airborne Dust Proxy",
    "volcanic_ash_enhanced": "Enhanced Volcanic Ash RGB",
    "volcanic_so2_enhanced": "Enhanced Volcanic SO₂ RGB",
    "silicate_ash_rgb": "Silicate Ash RGB",
    "ash_dust_discrimination": "Ash / Dust Discrimination",
    "split_window_ash": "Split-Window Ash RGB",
    "cloud_phase_thermal": "Thermal Cloud Phase",
    "cloud_height_thermal": "Thermal Cloud Height",
    "cloud_top_temperature_rgb": "Cloud-Top Temperature RGB",
    "cirrus_detection_rgb": "Cirrus Detection RGB",
    "thin_cirrus_rgb": "Thin Cirrus RGB",
    "opaque_ice_cloud_rgb": "Opaque Ice Cloud RGB",
    "low_cloud_thermal": "Thermal Low Cloud",
    "fog_depth_rgb": "Fog Depth RGB",
    "nocturnal_stratus_rgb": "Nocturnal Stratus RGB",
    "cloud_layering_rgb": "Cloud Layering RGB",
    "ice_water_phase_rgb": "Ice / Water Phase RGB",
    "convective_growth_rgb": "Convective Growth RGB",
    "severe_convection_thermal": "Severe Convection Thermal RGB",
    "tropical_convection_thermal": "Tropical Convection Thermal RGB",
    "overshooting_top_thermal": "Overshooting-Top Thermal RGB",
    "cold_ring_rgb": "Cold-Ring RGB",
    "storm_anvil_rgb": "Storm Anvil RGB",
    "rainfall_potential_rgb": "Rainfall Potential RGB",
    "lightning_risk_proxy": "Lightning-Risk Proxy RGB",
    "fire_hotspot_rgb": "Fire Hotspot RGB",
    "fire_context_rgb": "Fire Context RGB",
    "wildfire_temperature_rgb": "Wildfire Temperature RGB",
    "smoke_dust_day": "Daytime Smoke / Dust RGB",
    "burn_scar_rgb": "Burn Scar RGB",
    "vegetation_contrast_rgb": "Vegetation Contrast RGB",
    "vegetation_moisture_rgb": "Vegetation Moisture RGB",
    "snow_cloud_discrimination": "Snow / Cloud Discrimination",
    "daytime_cloud_phase_rgb": "Daytime Cloud Phase RGB",
    "daytime_fog_rgb": "Daytime Fog RGB",
    "coastal_aerosol_rgb": "Coastal Aerosol RGB",
    "land_ocean_contrast_rgb": "Land / Ocean Contrast RGB",
}
